laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('executivos', 'HomeController@executivos')->name('executivos');
    Route::get('cases/{divisao?}', 'CasesController@index')->name('cases');
    Route::get('depoimentos/{tipo?}', 'DepoimentosController@index')->name('depoimentos');
    Route::get('politica-de-privacidade', 'HomeController@politica')->name('politica');
    Route::get('contato-candidatos', 'HomeController@contatoCandidatos')->name('contato.candidatos');
    Route::post('contato-candidatos', 'HomeController@postCandidatos')->name('post.candidatos');
    Route::get('contato-empresas', 'HomeController@contatoEmpresas')->name('contato.empresas');
    Route::post('contato-empresas', 'HomeController@postEmpresas')->name('post.empresas');

    Route::get('meta-technology', 'MetaTechnologyController@index')->name('meta-technology');
    Route::post('meta-technology/contato', 'MetaTechnologyController@contato')->name('meta-technology.contato');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en') {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('configuracoes-meta-technology', 'ConfiguracoesMetaTechnologyController', ['only' => ['index', 'update']]);
        Route::get('meta-technology/contatos-recebidos/{contatos_recebidos}/toggle', ['as' => 'painel.meta-technology.contatos-recebidos.toggle', 'uses' => 'ContatosRecebidosTechController@toggle']);
        Route::resource('meta-technology/contatos-recebidos', 'ContatosRecebidosTechController');
        Route::resource('meta-technology/servicos', 'ServicosController');
        Route::resource('meta-technology', 'MetaTechnologyController', ['only' => ['index', 'update']]);
        Route::resource('depoimentos-empresas', 'DepoimentosEmpresasController');
        Route::resource('depoimentos-profissionais', 'DepoimentosProfissionaisController');
        Route::resource('cases', 'CasesController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('clientes', 'ClientesController');
        Route::resource('responsabilidade-social', 'ResponsabilidadeSocialController');
        Route::resource('executivos', 'ExecutivosController');
        Route::resource('selos', 'SelosController');
        Route::resource('video', 'VideoController', ['only' => ['index', 'update']]);
        Route::resource('textos', 'TextosController', ['only' => ['index', 'update']]);
        Route::resource('linha-do-tempo', 'LinhaDoTempoController');
        Route::resource('divisoes', 'DivisoesController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos-candidatos/{recebidos_candidatos}/toggle', ['as' => 'painel.contato.recebidos-candidatos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos-candidatos', 'ContatosRecebidosController');
        Route::get('contato/recebidos-empresas/{recebidos_empresas}/toggle', ['as' => 'painel.contato.recebidos-empresas.toggle', 'uses' => 'ContatosRecebidosEmpresasController@toggle']);
        Route::resource('contato/recebidos-empresas', 'ContatosRecebidosEmpresasController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CasesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CasesRequest;
use App\Http\Controllers\Controller;

use App\Models\Casemeta;

class CasesController extends Controller
{
    private $divisoes = [
        'meta-bpo'        => 'Meta BPO',
        'meta-executivos' => 'Meta Executivos',
        'meta-talentos'   => 'Meta Talentos',
        'meta-technology' => 'Meta Technology'
    ];

    public function __construct() {
        view()->share('divisoes', $this->divisoes);
    }

    public function index(Request $request)
    {
        $filtro = $request->get('filtro') ?: 'meta-bpo';

        $registros = Casemeta::where('divisao', $filtro)->ordenados()->get();

        return view('painel.cases.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.cases.create');
    }

    public function store(CasesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['marca'])) $input['marca'] = Casemeta::upload_marca();

            Casemeta::create($input);

            return redirect()->route('painel.cases.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Casemeta $registro)
    {
        return view('painel.cases.edit', compact('registro'));
    }

    public function update(CasesRequest $request, Casemeta $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['marca'])) $input['marca'] = Casemeta::upload_marca();

            $registro->update($input);

            return redirect()->route('painel.cases.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Casemeta $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.cases.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;

class ClientesController extends Controller
{
    public function index()
    {
        $imagens = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('imagens'));
    }

    public function show(Cliente $imagem)
    {
        return $imagem;
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();
            $input['marca'] = Cliente::upload_marca();

            $imagem = Cliente::create($input);

            $view = view('painel.clientes.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar marca: '.$e->getMessage();

        }
    }

    public function destroy(Cliente $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.clientes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesMetaTechnologyController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesMetaTechnologyRequest;
use App\Http\Controllers\Controller;

use App\Models\ConfiguracoesMetaTechnology;

class ConfiguracoesMetaTechnologyController extends Controller
{
    public function index()
    {
        $registro = ConfiguracoesMetaTechnology::first();

        return view('painel.configuracoes-meta-technology.edit', compact('registro'));
    }

    public function update(ConfiguracoesMetaTechnologyRequest $request, ConfiguracoesMetaTechnology $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = ConfiguracoesMetaTechnology::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes-meta-technology.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos-candidatos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos-candidatos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosEmpresasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebidoEmpresa;

class ContatosRecebidosEmpresasController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebidoEmpresa::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos-empresas.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebidoEmpresa $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos-empresas.show', compact('contato'));
    }

    public function destroy(ContatoRecebidoEmpresa $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos-empresas.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebidoEmpresa $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos-empresas.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DivisoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DivisoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Divisoes;

class DivisoesController extends Controller
{
    public function index()
    {
        $registro = Divisoes::first();

        return view('painel.divisoes.edit', compact('registro'));
    }

    public function update(DivisoesRequest $request, Divisoes $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.divisoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ $config->nome_do_site }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName()) || str_is('painel.configuracoes*', Route::currentRouteName())) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(str_is('painel.configuracoes*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(str_is('painel.usuarios*', Route::currentRouteName())) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li class="dropdown @if(str_is('painel.textos*', Route::currentRouteName()) || str_is('painel.banners*', Route::currentRouteName()) || str_is('painel.divisoes*', Route::currentRouteName()) || str_is('painel.linha-do-tempo*', Route::currentRouteName()) || str_is('painel.video*', Route::currentRouteName()) || str_is('painel.selos*', Route::currentRouteName()) || str_is('painel.executivos*', Route::currentRouteName()) || str_is('painel.responsabilidade-social*', Route::currentRouteName()) || str_is('painel.clientes*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Home
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.textos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.textos.index') }}">Textos</a>
            </li>
        	<li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        		<a href="{{ route('painel.banners.index') }}">Banners</a>
        	</li>
            <li @if(str_is('painel.divisoes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.divisoes.index') }}">Divisões</a>
            </li>
            <li @if(str_is('painel.linha-do-tempo*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.linha-do-tempo.index') }}">Linha do Tempo</a>
            </li>
            <li @if(str_is('painel.video*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.video.index') }}">Vídeo</a>
            </li>
            <li @if(str_is('painel.selos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.selos.index') }}">Selos</a>
            </li>
            <li @if(str_is('painel.executivos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.executivos.index') }}">Executivos</a>
            </li>
            <li @if(str_is('painel.responsabilidade-social*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.responsabilidade-social.index') }}">Responsabilidade Social</a>
            </li>
            <li @if(str_is('painel.clientes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.clientes.index') }}">Clientes</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.cases*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.cases.index') }}">Cases</a>
    </li>
    <li class="dropdown @if(str_is('painel.depoimentos*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Depoimentos
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.depoimentos-empresas*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.depoimentos-empresas.index') }}">Empresas</a>
            </li>
            <li @if(str_is('painel.depoimentos-profissionais*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.depoimentos-profissionais.index') }}">Profissionais</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos + $contatosNaoLidosEmpresas >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos + $contatosNaoLidosEmpresas }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos-candidatos.index') }}">
                Contatos Recebidos (Candidatos)
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
            <li><a href="{{ route('painel.contato.recebidos-empresas.index') }}">
                Contatos Recebidos (Empresas)
                @if($contatosNaoLidosEmpresas >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidosEmpresas }}</span>
                @endif
            </a></li>
        </ul>
    </li>
    <li @if(str_is('painel.politica-de-privacidade*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.politica-de-privacidade.index') }}">Política de Privacidade</a>
    </li>
    <li class="dropdown @if(str_is('painel.meta-technology*', Route::currentRouteName()) || str_is('painel.configuracoes-meta-technology*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Meta Technology
            @if($contatosNaoLidosTech >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidosTech }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.meta-technology.index', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.meta-technology.index') }}">Meta Technology</a>
            </li>
            <li @if(str_is('painel.meta-technology.servicos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.meta-technology.servicos.index') }}">Serviços</a>
            </li>
            <li class="divider"></li>
            <li @if(str_is('painel.meta-technology.contatos-recebidos*', Route::currentRouteName())) class="active" @endif><a href="{{ route('painel.meta-technology.contatos-recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidosTech >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidosTech }}</span>
                @endif
            </a></li>
            <li class="divider"></li>
            <li @if(str_is('painel.configuracoes-meta-technology*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.configuracoes-meta-technology.index') }}">Configurações</a>
            </li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ $config->nome_do_site }} - Painel Administrativo</title>

    {!! Tools::loadCss('vendor/bootswatch-dist/css/bootstrap.min.css') !!}
    {!! Tools::loadCss('css/vendor.painel.css') !!}
    {!! Tools::loadCss('css/painel.css') !!}
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    {!! Tools::loadJquery() !!}
    {!! Tools::loadJs('vendor/ckeditor/ckeditor.js') !!}
    {!! Tools::loadJs('js/vendor.painel.js') !!}
    {!! Tools::loadJs('js/painel.js') !!}
</body>
</html>