laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('executivos', 'HomeController@executivos')->name('executivos');
    Route::get('cases/{divisao?}', 'CasesController@index')->name('cases');
    Route::get('depoimentos/{tipo?}', 'DepoimentosController@index')->name('depoimentos');
    Route::get('politica-de-privacidade', 'HomeController@politica')->name('politica');
    Route::get('contato-candidatos', 'HomeController@contatoCandidatos')->name('contato.candidatos');
    Route::post('contato-candidatos', 'HomeController@postCandidatos')->name('post.candidatos');
    Route::get('contato-empresas', 'HomeController@contatoEmpresas')->name('contato.empresas');
    Route::post('contato-empresas', 'HomeController@postEmpresas')->name('post.empresas');

    Route::get('meta-technology', 'MetaTechnologyController@index')->name('meta-technology');
    Route::post('meta-technology/contato', 'MetaTechnologyController@contato')->name('meta-technology.contato');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en') {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
		Route::resource('configuracoes-meta-technology', 'ConfiguracoesMetaTechnologyController', ['only' => ['index', 'update']]);
        Route::get('meta-technology/contatos-recebidos/{contatos_recebidos}/toggle', ['as' => 'painel.meta-technology.contatos-recebidos.toggle', 'uses' => 'ContatosRecebidosTechController@toggle']);
        Route::resource('meta-technology/contatos-recebidos', 'ContatosRecebidosTechController');
        Route::resource('meta-technology/servicos', 'ServicosController');
        Route::resource('meta-technology', 'MetaTechnologyController', ['only' => ['index', 'update']]);
        Route::resource('depoimentos-empresas', 'DepoimentosEmpresasController');
        Route::resource('depoimentos-profissionais', 'DepoimentosProfissionaisController');
        Route::resource('cases', 'CasesController');
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::resource('clientes', 'ClientesController');
        Route::resource('responsabilidade-social', 'ResponsabilidadeSocialController');
        Route::resource('executivos', 'ExecutivosController');
        Route::resource('selos', 'SelosController');
        Route::resource('video', 'VideoController', ['only' => ['index', 'update']]);
        Route::resource('textos', 'TextosController', ['only' => ['index', 'update']]);
        Route::resource('linha-do-tempo', 'LinhaDoTempoController');
        Route::resource('divisoes', 'DivisoesController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);

        Route::get('contato/recebidos-candidatos/{recebidos_candidatos}/toggle', ['as' => 'painel.contato.recebidos-candidatos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos-candidatos', 'ContatosRecebidosController');
        Route::get('contato/recebidos-empresas/{recebidos_empresas}/toggle', ['as' => 'painel.contato.recebidos-empresas.toggle', 'uses' => 'ContatosRecebidosEmpresasController@toggle']);
        Route::resource('contato/recebidos-empresas', 'ContatosRecebidosEmpresasController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CasesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CasesRequest;
use App\Http\Controllers\Controller;

use App\Models\Casemeta;

class CasesController extends Controller
{
    private $divisoes = [
        'meta-bpo'        => 'Meta BPO',
        'meta-executivos' => 'Meta Executivos',
        'meta-talentos'   => 'Meta Talentos',
        'meta-technology' => 'Meta Technology'
    ];

    public function __construct() {
        view()->share('divisoes', $this->divisoes);
    }

    public function index(Request $request)
    {
        $filtro = $request->get('filtro') ?: 'meta-bpo';

        $registros = Casemeta::where('divisao', $filtro)->ordenados()->get();

        return view('painel.cases.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.cases.create');
    }

    public function store(CasesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['marca'])) $input['marca'] = Casemeta::upload_marca();

            Casemeta::create($input);

            return redirect()->route('painel.cases.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Casemeta $registro)
    {
        return view('painel.cases.edit', compact('registro'));
    }

    public function update(CasesRequest $request, Casemeta $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['marca'])) $input['marca'] = Casemeta::upload_marca();

            $registro->update($input);

            return redirect()->route('painel.cases.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Casemeta $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.cases.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;

class ClientesController extends Controller
{
    public function index()
    {
        $imagens = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('imagens'));
    }

    public function show(Cliente $imagem)
    {
        return $imagem;
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();
            $input['marca'] = Cliente::upload_marca();

            $imagem = Cliente::create($input);

            $view = view('painel.clientes.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar marca: '.$e->getMessage();

        }
    }

    public function destroy(Cliente $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.clientes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesMetaTechnologyController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesMetaTechnologyRequest;
use App\Http\Controllers\Controller;

use App\Models\ConfiguracoesMetaTechnology;

class ConfiguracoesMetaTechnologyController extends Controller
{
    public function index()
    {
        $registro = ConfiguracoesMetaTechnology::first();

        return view('painel.configuracoes-meta-technology.edit', compact('registro'));
    }

    public function update(ConfiguracoesMetaTechnologyRequest $request, ConfiguracoesMetaTechnology $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = ConfiguracoesMetaTechnology::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes-meta-technology.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos-candidatos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos-candidatos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosEmpresasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebidoEmpresa;

class ContatosRecebidosEmpresasController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebidoEmpresa::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos-empresas.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebidoEmpresa $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos-empresas.show', compact('contato'));
    }

    public function destroy(ContatoRecebidoEmpresa $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos-empresas.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebidoEmpresa $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos-empresas.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DivisoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DivisoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Divisoes;

class DivisoesController extends Controller
{
    public function index()
    {
        $registro = Divisoes::first();

        return view('painel.divisoes.edit', compact('registro'));
    }

    public function update(DivisoesRequest $request, Divisoes $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.divisoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/executivos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Executivos /</small> Adicionar Executivo</h2>
    </legend>

    {!! Form::open(['route' => 'painel.executivos.store', 'files' => true]) !!}

        @include('painel.executivos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/executivos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Executivos /</small> Editar Executivo</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.executivos.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.executivos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/executivos/form.blade.php
@include('painel.common.flash')

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/executivos/'.$registro->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('nome', 'Nome') !!}
    {!! Form::text('nome', null, ['class' => 'form-control']) !!}
</div>

<hr>

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('cargo_pt', 'Cargo PT') !!}
            {!! Form::text('cargo_pt', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('texto_pt', 'Texto PT') !!}
            {!! Form::textarea('texto_pt', null, ['class' => 'form-control', 'style' => 'resize:none']) !!}
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            {!! Form::label('cargo_en', 'Cargo EN') !!}
            {!! Form::text('cargo_en', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('texto_en', 'Texto EN') !!}
            {!! Form::textarea('texto_en', null, ['class' => 'form-control', 'style' => 'resize:none']) !!}
        </div>
    </div>
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.executivos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/executivos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Executivos
            <a href="{{ route('painel.executivos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Executivo</a>
        </h2>
    </legend>


    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="executivos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Imagem</th>
                <th>Nome</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td><img src="{{ asset('assets/img/executivos/'.$registro->imagem) }}" style="width: 100%; max-width:150px;" alt=""></td>
                <td>{{ $registro->nome }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.executivos.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.executivos.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection